/* Gannoe Media — shared filler media set.
   Swap src/thumb with real work later. Videos are public Google sample clips. */
window.GM_MEDIA = [
  { id: 'v1', type: 'video', cat: 'Highlights', title: 'State Final — Game Day Reel',
    thumb: 'https://picsum.photos/seed/gm-football/900/560',
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4' },
  { id: 'i1', type: 'image', cat: 'Portraits', title: 'Senior Portrait — №7',
    thumb: 'https://picsum.photos/seed/gm-port1/900/560',
    src: 'https://picsum.photos/seed/gm-port1/1800/1120' },
  { id: 'v2', type: 'video', cat: 'Commercial', title: 'Main Street Coffee — :30 Spot',
    thumb: 'https://picsum.photos/seed/gm-coffee/900/560',
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4' },
  { id: 'i2', type: 'image', cat: 'Highlights', title: 'Friday Lights — Sideline',
    thumb: 'https://picsum.photos/seed/gm-side/900/560',
    src: 'https://picsum.photos/seed/gm-side/1800/1120' },
  { id: 'v3', type: 'video', cat: 'Recruiting', title: 'QB1 — Recruiting Tape',
    thumb: 'https://picsum.photos/seed/gm-qb/900/560',
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4' },
  { id: 'i3', type: 'image', cat: 'Portraits', title: 'Team Captains — Studio',
    thumb: 'https://picsum.photos/seed/gm-cap/900/560',
    src: 'https://picsum.photos/seed/gm-cap/1800/1120' },
  { id: 'v4', type: 'video', cat: 'Events', title: 'Rivalry Night — Aftermovie',
    thumb: 'https://picsum.photos/seed/gm-night/900/560',
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4' },
  { id: 'i4', type: 'image', cat: 'Commercial', title: 'Gym Launch — Key Visual',
    thumb: 'https://picsum.photos/seed/gm-gym/900/560',
    src: 'https://picsum.photos/seed/gm-gym/1800/1120' },
  { id: 'i5', type: 'image', cat: 'Highlights', title: 'Hoops — Buzzer Beater',
    thumb: 'https://picsum.photos/seed/gm-hoops/900/560',
    src: 'https://picsum.photos/seed/gm-hoops/1800/1120' },
  { id: 'i6', type: 'image', cat: 'Portraits', title: 'Coach K — Editorial',
    thumb: 'https://picsum.photos/seed/gm-coach/900/560',
    src: 'https://picsum.photos/seed/gm-coach/1800/1120' },
  { id: 'v5', type: 'video', cat: 'Commercial', title: 'Auto Detail Co. — Brand Film',
    thumb: 'https://picsum.photos/seed/gm-auto/900/560',
    src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4' },
  { id: 'i7', type: 'image', cat: 'Events', title: 'Homecoming — Crowd',
    thumb: 'https://picsum.photos/seed/gm-crowd/900/560',
    src: 'https://picsum.photos/seed/gm-crowd/1800/1120' },
  { id: 'i8', type: 'image', cat: 'Recruiting', title: 'Combine Day — 40 Time',
    thumb: 'https://picsum.photos/seed/gm-combine/900/560',
    src: 'https://picsum.photos/seed/gm-combine/1800/1120' },
  { id: 'i9', type: 'image', cat: 'Highlights', title: 'Lacrosse — Spring Reel Still',
    thumb: 'https://picsum.photos/seed/gm-lax/900/560',
    src: 'https://picsum.photos/seed/gm-lax/1800/1120' },
  { id: 'i10', type: 'image', cat: 'Portraits', title: 'Senior Banners — Class of 26',
    thumb: 'https://picsum.photos/seed/gm-banner/900/560',
    src: 'https://picsum.photos/seed/gm-banner/1800/1120' },
  { id: 'i11', type: 'image', cat: 'Events', title: 'Signing Day — Ceremony',
    thumb: 'https://picsum.photos/seed/gm-sign/900/560',
    src: 'https://picsum.photos/seed/gm-sign/1800/1120' },
];
